# Generated by Django 5.1.6 on 2025-03-14 06:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteMaltrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reporte', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del caso')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='evidencias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'mp4', 'mp3'])])),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='maltrato_animal.reportemaltrato')),
            ],
        ),
    ]
