# Generated by Django 5.1.6 on 2025-03-14 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltrato_animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemaltrato',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])]),
        ),
    ]
