# Generated by Django 5.1.6 on 2025-03-14 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltrato_animal', '0002_reportemaltrato_audio_reportemaltrato_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemaltrato',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='nombre_completo',
            field=models.CharField(default='Nombre Apellido', max_length=255, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='telefono',
            field=models.CharField(default='1234567890', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Número de teléfono inválido.')], verbose_name='Número de teléfono'),
        ),
    ]
