# Generated by Django 5.1.6 on 2025-03-14 22:16

import django.db.models.deletion
import maltrato_animal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltrato_animal', '0003_reportemaltrato_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia',
            name='archivo',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='id_reporte',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='reportemaltrato',
            name='video',
        ),
        migrations.AddField(
            model_name='evidencia',
            name='imagen',
            field=models.ImageField(default='default.jpg', upload_to='maltrato_animal/', validators=[maltrato_animal.models.validar_extension_imagen]),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='estado_conservacion',
            field=models.CharField(choices=[('en_peligro', 'En Peligro'), ('invasora', 'Invasora'), ('comun', 'Común')], default='comun', max_length=15),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='tipo_especie',
            field=models.CharField(choices=[('fauna', 'Fauna'), ('flora', 'Flora')], default='fauna', max_length=10),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='maltrato_animal.reportemaltrato'),
        ),
        migrations.AlterField(
            model_name='reportemaltrato',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
