# Generated by Django 5.1.6 on 2025-03-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maltrato_animal', '0004_remove_evidencia_archivo_remove_evidencia_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportemaltrato',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportemaltrato',
            name='telefono',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportemaltrato',
            name='estado_conservacion',
            field=models.CharField(choices=[('en_peligro', 'En Peligro'), ('invasora', 'Invasora'), ('comun', 'Común')], default='comun', max_length=20),
        ),
    ]
