# Generated by Django 5.2 on 2025-05-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EliminacionParcialAvistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField(default='No se especificó el motivo')),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminaciones_reportes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('alerta_enviada', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/imagenes/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reportes/videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='reportes/audios/')),
                ('latitud', models.CharField(blank=True, max_length=50, null=True)),
                ('longitud', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte'), max_length=255)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte')),
            ],
        ),
    ]
