# Generated by Django 5.1.6 on 2025-03-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='reporte',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='reportes/audios/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/imagenes/'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reportes/videos/'),
        ),
    ]
