# Generated by Django 5.1.6 on 2025-03-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_remove_reporte_foto_url_reporte_audio_reporte_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
