# Generated by Django 5.1.6 on 2025-04-07 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporte_latitud_reporte_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='reportes/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reportes/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
