# Generated by Django 5.1.6 on 2025-04-07 02:20

import django.core.validators
import reportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporte_audio_alter_reporte_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='reportes/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav']), reportes.models.validate_audio_size]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reportes/imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), reportes.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reportes/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov']), reportes.models.validate_video_size]),
        ),
    ]
