# Generated by Django 5.1.7 on 2025-04-07 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_eliminacionparcialreporte_reporte_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte'), max_length=255),
        ),
    ]
