# Generated by Django 5.1.6 on 2025-04-07 03:16

import django.core.validators
import reportes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_reporte_audio_alter_reporte_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='imagen',
            field=models.ImageField(upload_to='reportes/imagenes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), reportes.models.validate_image_size]),
        ),
    ]
