# Generated by Django 5.2 on 2025-05-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_alter_reporte_audio_alter_reporte_imagen_and_more'),
        ('reportes', '0005_alter_reporte_titulo'),
    ]

    operations = [
    ]
