# Generated by Django 5.2 on 2025-05-02 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.logentry'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
