# Generated by Django 5.2 on 2025-05-02 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('especie_peligro', 'Especie en Peligro'), ('especie_invasora', 'Especie Invasora'), ('reporte_maltrato', 'Reporte de Maltrato')], max_length=50)),
                ('url_relacionada', models.URLField(blank=True, null=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_ong', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_fundacion', models.DateField(blank=True, null=True)),
                ('area_enfoque', models.CharField(blank=True, max_length=100, null=True)),
                ('verificada', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_ong', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
