# Generated by Django 5.1.6 on 2025-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0003_alter_avistamiento_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avistamiento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avistamientos/'),
        ),
    ]
