# Generated by Django 5.1.6 on 2025-03-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0004_alter_avistamiento_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avistamiento',
            name='foto',
        ),
        migrations.CreateModel(
            name='ImagenAvistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='avistamientos/')),
                ('avistamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='avistamientos.avistamiento')),
            ],
        ),
    ]
