# Generated by Django 5.1.6 on 2025-03-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0005_remove_avistamiento_foto_imagenavistamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='avistamiento',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
