# Generated by Django 5.1.6 on 2025-03-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0006_avistamiento_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='avistamiento',
            name='estado_conservacion',
            field=models.CharField(choices=[('en_peligro', 'En Peligro'), ('invasora', 'Invasora'), ('comun', 'Común')], default='comun', max_length=15),
        ),
        migrations.AddField(
            model_name='avistamiento',
            name='tipo_especie',
            field=models.CharField(choices=[('fauna', 'Fauna'), ('flora', 'Flora')], default='fauna', max_length=10),
        ),
    ]
