# Generated by Django 5.1.7 on 2025-04-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0012_alter_avistamiento_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionParcialAvistamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título por defecto', max_length=255)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='avistamiento',
            name='titulo',
            field=models.CharField(default='Título por defecto', max_length=255),
        ),
    ]
