# Generated by Django 5.1.7 on 2025-04-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0015_alter_eliminacionparcialavistamiento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionparcialavistamiento',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
