# Generated by Django 5.2 on 2025-05-01 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0016_eliminacionparcialavistamiento_mensaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminacionparcialavistamiento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminaciones_avistamientos', to=settings.AUTH_USER_MODEL),
        ),
    ]
