# Generated by Django 5.2 on 2025-05-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avistamientos', '0016_eliminacionparcialavistamiento_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50, unique=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='avistamiento',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='avistamientos.hashtag'),
        ),
    ]
