# Generated by Django 5.2 on 2025-05-02 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('flora', 'Flora'), ('fauna', 'Fauna'), ('especies_en_peligro', 'Especies en Peligro'), ('conservacion', 'Conservación'), ('practicas_sostenibles', 'Prácticas Sostenibles')], max_length=50)),
                ('region', models.CharField(choices=[('andina', 'Región Andina'), ('caribe', 'Región Caribe'), ('pacifica', 'Región Pacífica'), ('orinoquia', 'Región Orinoquía'), ('amazonia', 'Región Amazonía'), ('insular', 'Región Insular')], default='andina', max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='articulos/imagenes/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='educacion_ambiental.articulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='imagen_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulo_principal', to='educacion_ambiental.imagenarticulo'),
        ),
        migrations.CreateModel(
            name='VideoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='articulos/videos/')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='educacion_ambiental.articulo')),
            ],
        ),
    ]
