# Generated by Django 5.2 on 2025-04-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacion_ambiental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='region',
            field=models.CharField(choices=[('andina', 'Región Andina'), ('caribe', 'Región Caribe'), ('pacifica', 'Región Pacífica'), ('orinoquia', 'Región Orinoquía'), ('amazonia', 'Región Amazonía'), ('insular', 'Región Insular')], default='andina', max_length=50),
        ),
    ]
